version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: snyk
    versions:
    - 1.440.1
    - 1.440.4
    - 1.440.5
    - 1.444.0
    - 1.446.0
    - 1.447.0
    - 1.448.0
    - 1.449.0
    - 1.452.0
    - 1.526.0
    - 1.528.0
    - 1.529.0
    - 1.530.0
    - 1.532.0
    - 1.538.0
    - 1.541.0
    - 1.563.0
    - 1.570.0
  - dependency-name: shadow-cljs
    versions:
    - 2.12.0
    - 2.12.1
    - 2.12.2
    - 2.12.3
    - 2.12.4
