version: 2
jobs:
  build:
    docker:
      - image: thheller/cljs-dev:latest

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      JABBA_HOME: /tmp/.jabba

    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-{{ checksum "shadow-cljs.edn" }}

      - run: cd libs/reagent && lein install
      - run: npx shadow-cljs info
      - run: npm install
      - run: npm run build
      - run: npm pack
      - run: mkdir -p artifacts && mv agiledigital-mule-preview-*.tgz artifacts/

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "shadow-cljs.edn" }}

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

      - store_artifacts:
          path: artifacts

  deploy:
    docker:
      - image: thheller/cljs-dev:latest
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run release
          command: npm run semantic-release

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: /master/